### ISSUE TITLE
foto word niet afgebeeld

### ISSUE THREAD

**Issue by LaraPirkner** [Captep58/Een-foto-zegt-meer-dan-woorden-75e428bc#1]
Voeg hem op een andere manier toe.

**Comment by LaraPirkner** [comment]
https://www.w3schools.com/html/html_images.asp hier kan je nog een keer kijken voor tips maar probeer de foto in de zelfde map als de indexfile te zetten en dan FotoNaam.FileType

**Comment by Captep58** [comment]
Bedoel je dat ik het afbeelding met een url adress zal coderen?

**Comment by LaraPirkner** [comment]
Je kan het beste de file van de foto in hetzelfde mapje zetten van de index.html .
dan moet je in jouw code veranderen naar bitacademy.jpg zo kan hij hem makkelijk vinden
![Screenshot_1](https://user-images.githubusercontent.com/54847633/64406560-69bf9580-d082-11e9-99e4-6d868643ec5d.png)
![Screenshot_2](https://user-images.githubusercontent.com/54847633/64406567-6e844980-d082-11e9-8026-d747b09f7f1d.png)
